server:
  port: 3081
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: bookingModule
        uri: http://localhost:3001/
        predicates:
        - Path=/booking/**
      - id: movieModule
        uri: http://localhost:3002/
        predicates:
        - Path=/movies/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka
  registerWithEureka:
       - true
  fetchRegistry:
       - true